---
title: "Teaching plan"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      warning = FALSE,
                      comment = NA)

```

\


```{r}
library(dplyr)
library(kableExtra)

options(knitr.kable.NA = '')

rio::import("teaching_plan.xlsx", sheet = "index") %>% 
  select(session, topic_num, topic, slides_title) %>% 
  filter(!is.na(topic_num)) %>% 
  group_by(topic_num, topic) %>% 
  summarise(sessions = length(unique(session)),
            contents = paste0(paste(slides_title, collapse = ". "),".")) %>%
  ungroup() %>% 
  mutate(block = paste0(topic_num, ". ", topic, " (", sessions, 
                        ifelse (sessions == 1, 
                                " session)",
                                " sessions)"))) %>% 
  select(Block = block, Contents = contents) %>% 
  knitr::kable() %>% 
  kable_styling(full_width = FALSE,  
                bootstrap_options = c("condensed", "striped")) %>% 
  column_spec(1, width = "40em") %>% 
  column_spec(2, width = "80em")

```

